apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: tanzu-java-web-app
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: tanzu-java-web-app
spec:
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/metric: "rps"
      autoscaling.knative.dev/target: "10"
      autoscaling.knative.dev/window: "10s"
      autoscaling.knative.dev/max-scale: "5"
      autoscaling.knative.dev/min-scale: "0"
  image: registry.cloud-garage.net/ages/tanzu-java-web-app-apps:latest
